fear
renatodex/fabulasegoblins-monorepo pull request #11
Opened 2022-06-25 20:27 UTC by thetheu

I hope i'm doing right with git commands and don't screw this up. Changes made:

- Create login index;
- Add flame_logo;

2022-07-08 05:32 UTC, renatodex requested changes
Algumas mudanças antes da gente aprovar!

2022-07-08 05:32 UTC, renatodex commented on sheet-manager/pages/components/tendadogoblin.jsx
> +}
Não é legal ter esses arquivos sem linha extra no final. Pode ver que o Github até coloca um sinal de menos vermelho.
Se a gente consertar isso, esse arquivo vai sair do review.

É só entrar nele e dar um enter basicamente!

2022-07-08 05:32 UTC, renatodex commented on sheet-manager/pages/components/input.jsx
> +}
Aqui também seria legal entrar no arquivo e dar um enter no final!

2022-07-08 05:32 UTC, renatodex commented on sheet-manager/pages/login/index.jsx
> +export default Login
Mesma coisa pro Login, entra nele, dá um enter no final e comita!

2022-07-19 00:52 UTC, renatodex requested changes
Pronto! Deixei algumas sugestões de alteração:

Além das minhas sugestões do review, ia sugerir alterarmos o `index.jsx` pra colocar links nos botões!

```diff
-            <Button>Crie sua Conta</Button>
+            <Button href="/login">Crie sua Conta</Button>
           </div>
           <div className="mt-5 pb-5">
-            <Button>Entrar</Button>
+            <Button href="/login">Entrar</Button>
```

E juro que é só!

2022-07-19 00:52 UTC, renatodex commented on sheet-manager/pages/components/input.jsx
> +            className="">
Eu adicionaria algumas classes padrões aqui:
`p-3.5 bg-transparent border-colombia-blue border rounded-md w-full`

Acho que isso funcionaria, mas pra usar o `colombia-blue`, você precisa adicionar no seu tailwind.config:

```
columbia-blue': '#CBD5E0',
```

2022-07-19 00:52 UTC, renatodex commented on sheet-manager/pages/components/input.jsx
> +            {children}
O `children` você pode remover aqui, porque não é necessário pro nosso caso!

2022-07-19 00:52 UTC, renatodex commented on sheet-manager/pages/login/index.jsx
> +      <img src="/logo_flame.png" className="m-auto pt-20" width={80}></img>
Não é muito bom colocar Paddings pra ajustar layout em elementos inline.
Ao invés disso eu criaria uma Div envolta dessa imagem pra isolar ela, e ai colocaria as classes na Div em si. Inclusive dá pra diminuir um pouco o Padding:

```html
<div className='m-auto pt-14'>
    <img src="logo_flame.png" />
</div>
```

2022-07-19 00:52 UTC, renatodex commented on sheet-manager/pages/login/index.jsx
> +      <div className="mx-6 mt-8">
Aqui eu mudaria um pouco o espaçamento, deixaria:

```html
<div className="mx-10 mt-14">
```

2022-07-19 00:52 UTC, renatodex commented on sheet-manager/pages/login/index.jsx
> +        </div>
Aqui percebi que você tá usando um Parágrafo normal ao invés do Input de texto. Por causa disso, não tá dando pra digitar nada nos "campos".

Então ao invés dos parágrafos, eu substituiria pelos Inputs, e também evitaria misturar os estilos de Layout com os estilos de Texto. 

Que tal isso:

Repare que eu tirei os estilos de texto, porque eles já estão contidos no componente do Input.

```jsx
import Input from '../components/input'

<div className='mt-4'>
    <Input type='text' name='email' placeholder='email' />
</div>
<div className='mt-4'>
    <Input type='password' name='password' placeholder='senha' />
</div>
```

2022-07-19 00:52 UTC, renatodex commented on sheet-manager/pages/login/index.jsx
> +        <p className=" text-sm ml-8">Esqueceu sua senha? <span className="text-aero-blue">Clique aqui para recuperar!</span></p>
Aqui eu percebi que você tá colocando o texto todo no Spam, sendo que no layout apenas o botão `Clique aqui` estava em azul, então fiz uma sugestão de como ficaria:

Também descartei as margens porque acredito que está bom da forma que está:

```jsx
<p className='pt-5'>
    Esqueceu sua senha?
    {' '}
    <a href="" className='text-aero-blue'>
        Clique aqui
    </a>
    {' '}
    para recuperar.
</p>
```

2022-07-19 00:52 UTC, renatodex commented on sheet-manager/pages/login/index.jsx
> +        </div>
Poderíamos tirar essa div inicial com o `px-4` e deixar dessa forma:

```jsx
<div className='mt-14'>
  <div>
    <Button>Crie sua Conta</Button>
  </div>
  <div className='m-auto text-center pt-3'>
    ou
  </div>
  <div className="mt-3 pb-5">
    <Button>Entrar</Button>
  </div>
</div>
```

2022-07-20 22:45 UTC, thetheu commented on sheet-manager/pages/login/index.jsx
> +      <img src="/logo_flame.png" className="m-auto pt-20" width={80}></img>
Aqui eu mantive o m-auto no próprio elemento da imagem, pois ele não estava aplicando quando colocado na div criada. 
<div className='pt-14'>
    <img className="m-auto" src="logo_flame.png" />
</div>

2022-07-21 17:55 UTC, renatodex requested changes
Fora isso tá lindo!

2022-07-21 17:55 UTC, renatodex commented on sheet-manager/pages/components/input.jsx
> +export default function Input({ children, type, name, placeholder }) {
Podemos remover essa variável `children` já que ela não tá sendo usada?

2022-08-05 21:40 UTC, renatodex approved these changes
Lgtm 🚢

2022-08-05 21:41 UTC, merged